### PR TITLE
Prepare for NPM

### LINKED ISSUE #3: Electron Environment?
I'd like to silence the logging by default.

Use Case:

* When this runs in Electron, I believe all the logging lines are necessary to track progress, or even prove it's working.
* When this runs as a FaaS, I don't believe all the lines are necessary all the time, and printing to the console DOES delay processing (I'm trying to shave milliseconds).

I'll happily rewrite the logging, are you amenable to at least setting an environment variable when you want logs?

### PR DESCRIPTION
**Pull request by jnovack**
1. Added `package.json` with sample data and the following packages:
* heroprotocol / xregexp (previous requirements)
* mocha/chai testing suite
* pino logging suite

2. Created a sample `test.js` to get us started.

3. Added logging and guessed on level of log types
* error - file did not process
* warn - processed but continuing with issues
* info - meh
* debug - main sections and program flow
* trace - individual pieces of data

4. Replaced `"` with `'` in all logging messages for consistency.

I envision v1.0.0 of the npm package to be:
* a version bump (from `6` to `7`) of `PARSER_VERSION`.
* you incorporated it in `stats-of-the-storm`
* `stats-of-the-storm` no longer has a `parser.js`

This can be very quick.  I can use it as a FaaS right now with feature parity to `stats-of-the-storm`.  I just want v1.0.0 to be no longer developing this in tandem with the `parser.js` file in `stats-of-the-storm` repo.

Closes #3

### CODE REVIEW

**Comment by ebshimizu** [comment]
wew this is happening real fast, going to need a bit of time to look things over and confirm compatibility with the existing parser/app combo

Quick comment from looking at the PR message (not the changes): I've been reserving parser whole number version bumps to indicate breaking changes to the output schema (specifically as it relates to stats of the storm). In this case, I wouldn't actually want to increment it to 7 (output format is the same). Would it also make sense then to set the npm package version to 6.x.x for consistency? there will be minor updates as heroes get added.

**Comment by jnovack** [comment]
> wew this is happening real fast, going to need a bit of time to look things over and confirm compatibility with the existing parser/app combo

no problem.  I get spurts of energy and basically I AGILE sprint when my time allows it.  my main concern is your (desktop) app works with minimal changes. apologies. :)  I get excited when I see a good project.

> indicate breaking changes to the output schema

I was hoping that number was a SCHEMA number.  So, yay!

> set the npm package version to 6.x.x for consistency

Totally and completely agree. The output IS the... output (for lack of a better word) of this module, so any breaking changes WOULD (also) be schema breaking.

I will bumping within 0.x.y as I modify and restructure the program (e.g. add tests, rewrite `battletags.js`, reorganize enum files) to signify that something has changed.

**Comment by jnovack** [comment]
`npm update`

both `heroprotocol` and `storm-replay` received updates to serve files and buffers.

You should be at:
* hots-parser v0.3.0
* heroprotocol v2.0.0-alpha.6
* storm-replay 0.3.0-alpha.6

**Comment by ebshimizu** [comment]
I'm not seeing 2.0.0-alpha.7 in the npm package repository. It says it only goes up to 2.0.0-alpha.5. :(

**Comment by jnovack** [comment]
sorry, didn't know you were downloading it from `npm`.  It was pushed to the git repo. it's on `npm` now.

all pieces were pushed to npm.

**Comment by ebshimizu** [comment]
ohhh they were pushed to your fork of nydus/heroprotocol. I completely missed that and alpha.5 happened to be in npm when I was testing. Will test out alpha.7 tonight.

**Comment by ebshimizu** [comment]
Ok! `alpha.7` works! I have been testing the parser as a submodule, but I don't expect any difficulties switching over to the npm package.

**Comment by jnovack** [comment]
I will probably `heroprotocol` v2.0.0 and `storm-replay` v0.3.0 on Sunday (I'm GMT-4). 

The goal (of this PR) is to get the `hots-parser` working completely as a separate module, independent of the application.  Once we're fully NPM packaged, I'll submit a PR for travis (travis-ci.org) or some other CI to auto-publish a new npm on commits to master.

Also, you are free to move this to the nydus org if you want (no pressure). 

How often does the parser change, every patch?

**Comment by ebshimizu** [comment]
Sounds good! I'll look out for the final changes this weekend and we can hopefully get this merged then.

As for parser changes:

Breaking changes (schema) happen infrequently. Some fields do change from patch to patch as Blizz adds more post-game stats (damage done, etc.), but I don't consider those to be breaking (they only ever add stats they don't remove them as far as I can tell).

Maintenance changes (non-schema changing) happen under the following circumstances:
* A new hero is added (single line change to add their attribute ID to the list of heroes)
* The internal id code for the "back" action changes. This happens rarely and unpredictably between major patches. Also a small change.
* I choose to refactor something (which I should really do more thoroughly eventually)

**Comment by jnovack** [comment]
That sounds reasonable. 

What needs to be done to ensure that someone doesn't have to download a new version of your app unnecessarily (i.e. a hero add, talent adds)?

In a new issue (on here) we should look for the parser to update itself (or accept a function from the parent application to update).

At a minimum, I would expect an update to `hots-parser` (perhaps `hots-parser.update()`) should call `heroes-talents.update()` and `heroprotocol.update()`, both of which are self-updating.

**Comment by ebshimizu** [comment]
I think the most important thing, for my app at least, is that the parser itself should not allow parsing anything newer than what it was tested on. The parser should probably declare a maximum supported build in its own script so that the other components can be updated independently at any time.

As for my app, if the modules have callable update functions it just comes down to engineering. I'll have to separate the auto-updating node modules from the read-only asar package and then it should be ok.

The one case where I can see this causing problems are when major breaking changes happen. I think it's ok to put that on the app developer side? I can make my app refuse to parse anything if the database version doesn't match the major parser version yet.

**Comment by jnovack** [comment]
You are killin' me Petey.

image

**Comment by ebshimizu** [comment]
my local directory is a little cluttered. 
Everything look good here? I'm ready to merge it if everything's set on your end.

**Comment by jnovack** [comment]
Just need a confirmation from Windows that the new "smaller" replay files are still parsable.  I'll v0.3.0 storm-replay, then v2.0.0 heroprotocol, then I will version this as... v6.36.0?

Is that correct?

**Comment by jnovack** [comment]
That's what the you made the `test_data/` directory for that's already in `.gitignore`, your test... data.

**Comment by ebshimizu** [comment]
I'll run a match from PTR through this weekend. From what I can tell, all the relevant data is still there, but I haven't yet run a complete match through.

Make sense to me to keep the minor version in sync with hots, so 6.36.0 sounds good.

**Comment by ebshimizu** [comment]
well i sat in queue for 20 minutes and i'm not convinced there are real people on PTR anymore.
Manual inspection of the heroprotocol output of an AI game doesn't show any red flags, so whatever they did doesn't seem to have affected the parsing output as far as I can tell. We can always wait for live as well and test in then.

**Comment by jnovack** [comment]
Might as well, it's only 2 days away.  Will wait.

**Comment by ebshimizu** [comment]
All of the replays are parsing cleanly. Whatever they changed doesn't appear to affect the decompressed data somehow (but the files do seem smaller).

Should be good to go with 6.36

**Pull request merged**
